export enum EVENTS {
  GET_LOCALE = "TS_GET_LOCALE",
  SET_LOCALE = "TS_SET_LOCALE", 

  GET_CREDENTIALS_PROVIDED = "TS_GET_CREDENTIALS_PROVIDED",
  SET_CREDENTIALS_PROVIDED = "TS_SET_CREDENTIALS_PROVIDED",
  
  SAVE_CREDENTIALS = "TS_SAVE_CREDENTIALS",

  GET_SALES_CHANNELS_PROVIDED = "TS_GET_SALES_CHANNELS_PROVIDED",
  SET_SALES_CHANNELS_PROVIDED = "TS_SET_SALES_CHANNELS_PROVIDED",

  SAVE_MAPPED_CHANNEL = "TS_SAVE_MAPPED_CHANNEL",
  GET_MAPPED_CHANNELS = "TS_GET_MAPPED_CHANNELS",
  SET_MAPPED_CHANNELS = "TS_SET_MAPPED_CHANNELS",

  GET_TRUSTBADGE_CONFIGURATION_PROVIDED = "TS_GET_TRUSTBADGE_CONFIGURATION_PROVIDED",
  SET_TRUSTBADGE_CONFIGURATION_PROVIDED = "TS_SET_TRUSTBADGE_CONFIGURATION_PROVIDED",

  SAVE_TRUSTBADGE_CONFIGURATION = "TS_SAVE_TRUSTBADGE_CONFIGURATION",

  GET_LOCATION_FOR_WIDGET = "TS_GET_LOCATION_FOR_WIDGET",
  SET_LOCATION_FOR_WIDGET = "TS_SET_LOCATION_FOR_WIDGET",

  GET_AVAILABLE_PRODUCT_IDENTIFIERS = "TS_GET_AVAILABLE_PRODUCT_IDENTIFIERS",
  SET_AVAILABLE_PRODUCT_IDENTIFIERS = "TS_SET_AVAILABLE_PRODUCT_IDENTIFIERS",

  SAVE_WIDGET_CHANGES = "TS_SAVE_WIDGET_CHANGES",

  GET_WIDGET_PROVIDED = "TS_GET_WIDGET_PROVIDED",
  SET_WIDGET_PROVIDED = "TS_SET_WIDGET_PROVIDED",

  ACTIVATE_PRODUCT_REVIEW_FOR_CHANNEL = "TS_ACTIVATE_PRODUCT_REVIEW_FOR_CHANNEL",
  DEACTIVATE_PRODUCT_REVIEW_FOR_CHANNEL = "TS_DEACTIVATE_PRODUCT_REVIEW_FOR_CHANNEL",
  GET_PRODUCT_REVIEW_FOR_CHANNEL = "TS_GET_PRODUCT_REVIEW_FOR_CHANNEL",
  SET_PRODUCT_REVIEW_FOR_CHANNEL = "TS_SET_PRODUCT_REVIEW_FOR_CHANNEL",

  SAVE_USE_ESTIMATED_DELIVERY_DATE_FOR_CHANNEL = "TS_SAVE_USE_ESTIMATED_DELIVERY_DATE_FOR_CHANNEL",
  GET_USE_ESTIMATED_DELIVERY_DATE_FOR_CHANNEL = "TS_GET_USE_ESTIMATED_DELIVERY_DATE_FOR_CHANNEL",
  SET_USE_ESTIMATED_DELIVERY_DATE_FOR_CHANNEL = "TS_SET_USE_ESTIMATED_DELIVERY_DATE_FOR_CHANNEL",
  SAVE_USE_EVENTS_BY_ORDER_STATUS_FOR_CHANNEL = "TS_SAVE_USE_EVENTS_BY_ORDER_STATUS_FOR_CHANNEL",
  GET_USE_EVENTS_BY_ORDER_STATUS_FOR_CHANNEL = "TS_GET_USE_EVENTS_BY_ORDER_STATUS_FOR_CHANNEL",
  SET_USE_EVENTS_BY_ORDER_STATUS_FOR_CHANNEL = "TS_SET_USE_EVENTS_BY_ORDER_STATUS_FOR_CHANNEL",

  GET_USED_ORDER_STATUSES = "TS_GET_USED_ORDER_STATUSES",
  SET_USED_ORDER_STATUSES = "TS_SET_USED_ORDER_STATUSES",
  SAVE_USED_ORDER_STATUSES = "TS_SAVE_USED_ORDER_STATUSES",

  GET_AVAILABLE_ORDER_STATUSES = "TS_GET_AVAILABLE_ORDER_STATUSES",
  SET_AVAILABLE_ORDER_STATUSES = "TS_SET_AVAILABLE_ORDER_STATUSES",

  EXPORT_PREVIOUS_ORDER = "TS_EXPORT_PREVIOUS_ORDER",
  SET_EXPORT_PREVIOUS_ORDER = "TS_SET_EXPORT_PREVIOUS_ORDER",

  GET_INFORMATION_OF_SYSTEM = "TS_GET_INFORMATION_OF_SYSTEM",
  SET_INFORMATION_OF_SYSTEM = "TS_SET_INFORMATION_OF_SYSTEM",

  DISCONNECTED = "TS_DISCONNECTED",
  SET_DISCONNECTED = "TS_SET_DISCONNECTED",

  CLOSE_CONNECTOR = "TS_CLOSE_CONNECTOR",

  NOTIFICATION = "TS_NOTIFICATION",

  ERROR = "TS_ERROR",
}
