version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  node: circleci/node@5.1.0
  cloudfront-s3-deploy: trustedshops-public/cloudfront-s3-deploy@3.0.0

anchors:
  deploy_defaults: &deploy_defaults
    attach_workspace: true
    pattern: '/events/*'
    context:
      - connect-team
    requires:
      - build

executors:
  building:
    docker:
      - image: cimg/node:18.12

jobs:
  build:
    executor: building
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build library
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist/

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - cloudfront-s3-deploy/sync_and_invalidate:
          name: deploy_to_qa
          <<: *deploy_defaults
          bucket_name: ts-connect-qa-trustedshops-app
          distribution_id: E2HC1Y83IARISC
          aws_iam_web_identity_role_arn: $WEB_IDENTITY_ROLE_ARN_QA
          filters:
            branches:
              only:
                - main
      - cloudfront-s3-deploy/sync_and_invalidate:
          name: deploy_to_prod
          <<: *deploy_defaults
          bucket_name: ts-connect-prod-trustedshops-app
          distribution_id: E17P53GJGRBTBG
          aws_iam_web_identity_role_arn: $WEB_IDENTITY_ROLE_ARN_PROD
          filters:
            branches:
              only:
                - never
