version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  node: circleci/node@5.1.0
  cloudfront-s3-deploy: trustedshops-public/cloudfront-s3-deploy@3.0.0
  semantic-release: trustedshops-public/semantic-release@5.0.0
  deterministic-zip: timo-reymann/deterministic-zip@1.0.0

anchors:
  deploy_defaults: &deploy_defaults
    attach_workspace: true
    additional_args: "--exclude *.zip"
    remote: /events/
    pattern: '/events/*'
    context:
      - connect-team
    requires:
      - build
  filter_only_main: &filter_only_main
    filters:
      branches:
        only: main

executors:
  building:
    docker:
      - image: cimg/node:18.12

jobs:
  build:
    executor: building
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - deterministic-zip/install
      - run:
          name: Build library
          command: yarn build
      - deterministic-zip/zip:
          source: dist/
          target: dist/lib.zip
      - persist_to_workspace:
          root: .
          paths:
            - dist/
  semantic-release:
    executor: semantic-release/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - semantic-release/execute

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - cloudfront-s3-deploy/sync_and_invalidate:
          name: deploy_to_qa
          <<: *deploy_defaults
          <<: *filter_only_main
          bucket_name: ts-connect-qa-trustedshops-app
          distribution_id: E2HC1Y83IARISC
          aws_iam_web_identity_role_arn: $WEB_IDENTITY_ROLE_ARN_QA
      #- semantic-release:
      #    <<: *filter_only_main
      #    requires:
      #      - build
      - cloudfront-s3-deploy/sync_and_invalidate:
          name: deploy_to_prod
          <<: *deploy_defaults
          bucket_name: ts-connect-prod-trustedshops-app
          distribution_id: E17P53GJGRBTBG
          aws_iam_web_identity_role_arn: $WEB_IDENTITY_ROLE_ARN_PROD
          requires:
            - build
          filters:
            tags:
              only:
                - /.*/
